### ISSUE TITLE
Timestamp issue

### ISSUE THREAD

**Issue by Bradox** [logstash-plugins/logstash-codec-compress_spooler#2] opened 2014-12-09 21:05 UTC
Enabling the codec compress_spooler for rabbitmq output throws an exception:

Error encoding event {:exception=>#<TypeError: The field '@timestamp' must be a (LogStash::Timestamp, not a Float (1418158061.228)>, :event=>#<LogStash::Event:0x2f4b275c @metadata={}, @accessors=#<LogStash::Util::Accessors:0x6f052145 @store={"message"=>"assdasd", "@version"=>"1", "@timestamp"=>"2014-12-09T20:47:41.228Z", "host"=>"alejandro-lp"}, @lut={"host"=>[{"message"=>"assdasd", "@version"=>"1", "@timestamp"=>"2014-12-09T20:47:41.228Z", "host"=>"alejandro-lp"}, "host"], "@timestamp"=>[{"message"=>"assdasd", "@version"=>"1", "@timestamp"=>"2014-12-09T20:47:41.228Z", "host"=>"alejandro-lp"}, "@timestamp"]}>, @logger=#<Cabin::Channel:0x4f1b0c33 @subscriber_lock=#<Mutex:0x643d12f>, @data={}, @metrics=#<Cabin::Metrics:0x4e5a67df @channel=#<Cabin::Channel:0x4f1b0c33 ...>, @metrics={}, @metrics_lock=#<Mutex:0x115989a9>>, @subscribers={2002=>#<Cabin::Outputs::IO:0x324e48f0 @lock=#<Mutex:0x1777051a>, @io=#<IO:fd 1>>}, @level=:warn>, @data={"message"=>"assdasd", "@version"=>"1", "@timestamp"=>"2014-12-09T20:47:41.228Z", "host"=>"alejandro-lp"}, @metadata_accessors=#<LogStash::Util::Accessors:0x6eff9ff @store={}, @lut={}>, @cancelled=false>, :level=>:warn}

LS config:

rabbitmq{
                codec => compress_spooler {
                     #compress_level => 6
                     #spool_size => 10
                }
                host => "localhost"
                durable => true
                exchange => "amq.topic"
                exchange_type => "topic"
                port => 5672
                user => "guest"
                password => "guest"
        }

This seems to be fixed in this fork:

https://github.com/coolacid/logstash-contrib/tree/LOGSTASH-1812

**Comment by purbon** [comment] 2015-07-24 15:42
@Bradox I did some investigation on this and could not reproduce the issue. As you can see from test in here https://github.com/logstash-plugins/logstash-codec-compress_spooler/blob/master/spec/codecs/compress_spooler_spec.rb the codec processes timestamp as expected. 

i really would like to get this down, can you let me know a sample input you/we can use to reproduce this error? From the exceptions in #4 or #5 I was not able to reproduce.

Thanks a lot man.

**Comment by purbon** [comment] 2015-07-24 16:19
Closing this until new data has arrived to let us reproduce. Looking forward to reopen if necessary.

**Closed by purbon** 2015-07-24 16:19 UTC
